service: stepfunctions-demo

plugins:
  - serverless-step-functions

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1

functions:
  add:
    handler: handler.add
  double:
    handler: handler.double
  counter:
    handler: handler.counter
  thrower:
    handler: handler.thrower

stepFunctions:
  stateMachines:
    hello:
      name: hello
      definition:
        Comment: hello world example
        StartAt: Add
        States:
          Add:
            Type: Task
            Resource:
              Fn::GetAtt: [add, Arn]
            Next: Double
          Double:
            Type: Task
            Resource:
              Fn::GetAtt: [double, Arn]
            Next: IsBigNumber
          IsBigNumber:
            Type: Choice
            Choices:
              - Variable: $
                NumericGreaterThan: 100
                Next: Pass
            Default: Counter
          Counter:
            Type: Task
            Resource:
              Fn::GetAtt: [counter, Arn]
            Next: Thrower
            Retry:
              - ErrorEquals: [States.ALL]
                MaxAttempts: 3
          Thrower:
            Type: Task
            Resource:
              Fn::GetAtt: [thrower, Arn]
            Next: Fail
            Catch:
              - ErrorEquals: [States.ALL]
                Next: Pass
          Fail:
            Type: Fail
            Error: "Badness"
            Cause: "We should have caught"
          Pass:
            Type: Pass
            End: true
